# Generated by Django 5.2.15 on 2026-08-13 12:29

from django.db import migrations, models


def clear_existing_email_verifications(apps, schema_editor):
    EmailVerification = apps.get_model(
        "accounts",
        "EmailVerification",
    )

    EmailVerification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_user_first_name_remove_user_last_name",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("registration", "Registration"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(
            clear_existing_email_verifications,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("registration", "Registration"),
                ],
                max_length=20,
            ),
        ),
    ]