# Generated by Django 5.2.15 on 2026-07-16 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_room_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesture', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='presence.human')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='presence.human')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='presence.moment')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='presence.human')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='presence.invitation')),
            ],
        ),
        migrations.AddField(
            model_name='moment',
            name='accepted_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='moment', to='presence.response'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('human',), name='unique_open_invitation_per_human'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(fields=('moment', 'human'), name='unique_presence_per_moment_and_human'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('human',), name='unique_active_presence_per_human'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('left_at__isnull', True), ('status', 'active')), models.Q(('left_at__isnull', False), ('status', 'completed')), _connector='OR'), name='presence_status_matches_left_at'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('human',), name='unique_pending_response_per_human'),
        ),
        migrations.AddConstraint(
            model_name='moment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status', 'completed')), _connector='OR'), name='moment_status_matches_ended_at'),
        ),
    ]
