# Generated by Django 5.2.15 on 2026-07-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_room_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesture', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='humans.human')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='humans.human')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='presence.moment')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='humans.human')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='presence.invitation')),
            ],
        ),
        migrations.AddField(
            model_name='moment',
            name='accepted_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='moment', to='presence.response'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('human',), name='unique_open_invitation_per_human'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(fields=('moment', 'human'), name='unique_presence_per_moment_and_human'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('human',), name='unique_pending_response_per_human'),
        ),
    ]
