# Generated by Django 5.2.15 on 2026-07-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesture', models.TextField()),
                ('media_stream', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moments', to='presence.human')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('gesture', 'Gesture'), ('response', 'Response')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memories', to='presence.human')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memories', to='presence.moment')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('participant', 'Participant')], max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='presence.human')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='presence.moment')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='presence.human')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='presence.moment')),
            ],
        ),
    ]
