# Generated by Django 5.2.15 on 2026-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0001_initial'),
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('invitation',), name='unique_accepted_response_per_invitation'),
        ),
    ]
